### ISSUE TITLE
GS1 barcode pulling ISBN instead

### ISSUE THREAD

**Issue by LuxorPPE** [WhyNotHugo/python-barcode#28]
Here is my code:
```
 import barcode
 from barcode.writer import ImageWriter
 varGS1 = barcode.get_barcode_class('gs1')
 varGS1out = varGS1(u'42053005383691149014', writer=ImageWriter)
 fullname = varGS1out.save('C:\\Users\\PaulPers\\Desktop\\GS1_barcode')
```
and I get the following error:
> Traceback (most recent call last):
>   File "<module1>", line 5, in <module>
>   File "C:\Users\PaulPers\AppData\Roaming\Python\Python37\site-packages\barcode\isxn.py", line 50, in __init__
>     raise WrongCountryCodeError('ISBN must start with 978 or 979.')
> barcode.errors.WrongCountryCodeError: ISBN must start with 978 or 979.

Thank you.

**Comment by WhyNotHugo** [comment]
This looks correct [[source]](https://en.wikipedia.org/wiki/International_Standard_Book_Number#Overview):

> for a 13-digit ISBN, a prefix element – a GS1 prefix: so far 978 or 979 have been made available by GS1

Do you have any reference as to that being wrong?

**Comment by WhyNotHugo** [comment]
Ah, sorry, the title clarifies this: you're using GS1, but this is a ISBN-only limitation. Good catch.
