### ISSUE TITLE
TypeError: string argument expected, got 'bytes' ?

### ISSUE THREAD

**Issue by jekoie** [WhyNotHugo/python-barcode#46]
the barcode run error in python3.6
```
import barcode
import io
from barcode.writer import ImageWriter
import traceback

fp = io.StringIO()
barcode.generate('gs1_128', 'iloveyou', writer=ImageWriter(), output=fp)
```

Traceback (most recent call last):
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-aa318e8f6722>", line 7, in <module>
    barcode.generate('gs1_128', 'iloveyou', writer=ImageWriter(), output=fp)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\barcode\__init__.py", line 80, in generate
    barcode.write(output, options, text)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\barcode\base.py", line 90, in write
    output.save(fp, format=self.writer.format)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PIL\Image.py", line 2088, in save
    save_handler(self, fp, filename)
  File "C:\Users\jekoie\AppData\Local\Programs\Python\Python36-32\lib\site-packages\PIL\PngImagePlugin.py", line 807, in _save
TypeError: string argument expected, got 'bytes'

**the python3.6 pillow treat raw code as bytes, but barcode treat as string, so it raise error?**
**another issue is  how can i create a barcode only show graph without number under the graph??**

**Comment by AlanSwenson** [comment]
@jekoie I _solved_ this but using `BytesIO()` instead of `StringIO()`

**Comment by WhyNotHugo** [comment]
I've updated the README, which was ridiculously outdates. Yes, `BytesIO` is the way to go.
