### ISSUE TITLE
Does not work on Raspberry Pi with either Python 2.7 or 3.5.3

### ISSUE THREAD

**Issue by peterantypas** [WhyNotHugo/python-barcode#78]
Installed with both pip and pip3. The ImageWriter class cannot be instantiated. This causes all example code to fail.

> Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> w = barcode.writer.ImageWriter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'barcode' is not defined
>>> from barcode.writer import ImageWriter
>>> w = ImageWriter()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not callable

**Comment by peterantypas** [comment]
This was caused by an incomplete install of Pillow, missing libtiff5.
