### ISSUE TITLE
Error when importing the barcode library

### ISSUE THREAD

**Issue by ferdinandsousa** [WhyNotHugo/python-barcode#99]
Executing 
`import barcode`
gives the traceback below:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/printo/.local/lib/python3.5/site-packages/barcode/__init__.py", line 11, in <module>
    from barcode.codex import Code128
  File "/home/printo/.local/lib/python3.5/site-packages/barcode/codex.py", line 5, in <module>
    from barcode.base import Barcode
  File "/home/printo/.local/lib/python3.5/site-packages/barcode/base.py", line 4, in <module>
    from barcode.writer import SVGWriter
  File "/home/printo/.local/lib/python3.5/site-packages/barcode/writer.py", line 335
    format: str
```

Environment info:
Python 3.5.2 64 bit
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

**Comment by WhyNotHugo** [comment]
Python 3.5 is no longer supported (no longer by upstream, nor by this library).

Upgrade to a modern version of python, or use an older version of this library.
